### ISSUE TITLE
Inventory Not Saving

### ISSUE THREAD

**Issue by Azurago** [bergerhealer/MyWorlds#1]
When 'useWorldInventories' is false, inventories wont save when a user logs out. When they log back in, it is back to the same as it was when they logged in last time. When I set that node to true, the server crashes.

I am using BK build 31. and MyWorlds build 5 (as listed on drone.io) 
Spigot 1.8.7 build #40 on McMyAdmin 2.5.4.0

Crash report: http://pastebin.com/PbLggeaT

**Comment by tmad40blue** [comment]
+1 on this issue, my server experiences the exact same problem. Hope there's a fix soon.

**Comment by mg-1999** [comment]
I am working on this now, only can't find the yet. So the search will continue!

**Comment by FriwiDev** [comment]
I will try to fix this issue aswell :) Thanks for reporting!

**Comment by Azurago** [comment]
It is half fixed. With useWorldInventories false, it does not save the inventory on log out. I noticed it does not save a gamemode switch either.  No error.

**Comment by bergerkiller** [comment]
I made changes to fix some world saving bugs that had to do with some old code saving player inventories by playername.dat instead of the player {UUID}. It properly saves and restores inventories for me, now. Please let me know if this bug still occurs with certain configurations and I will re-open the issue.
