### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CodeDoctorDE** [bergerhealer/MyWorlds#26]
It would be cool if this repository has a license to use some snippets in an own plugin

**Comment by weeryan17** [comment]
While yes this repo doesn't have a license berger has said in the past he doesn't really care what people do with it as long as they don't claim it as their own, basically MIT license. (technically he's fine with it being even slightly loser then that, but thats the best example I can give)

**Comment by CodeDoctorDE** [comment]
Okay, nice. Legally it's currently arr, you're not allowed to use it.
It would be cool if berger can add a license.
See here: https://choosealicense.com/no-permission/

**Comment by weeryan17** [comment]
> Okay, nice. Legally it's currently arr, you're not allowed to use it.
Technically yes (kinda, it's complicated because github TOS has some provisions of its own), practically no. The only issue that would come up is if berger sued you which based on what he said he's not going to do.

> It would be cool if berger can add a license.
> See here: https://choosealicense.com/no-permission/
I don't disagree with you there, as mentioned above though you don't need to worry about it, I'm sure berger will add one when he gets time.

I'm mostly informing you to not wait for berger to get around to it as he doesn't care what you do with his stuff for the most part.
