### ISSUE TITLE
Another nickname for a world

### ISSUE THREAD

**Issue by VIQingNiao** [bergerhealer/MyWorlds#27]
How to set it? Like the setting of plug-in Multiverse-Core, the alias of "Worlds" is "ABC". for in-game chat messages, "ABC" will replace "Worlds" to display them.

The setting of plug-in Multiverse-Core is like this.

![My_Worlds](https://user-images.githubusercontent.com/46963763/165345087-bb83deca-94c0-4b67-ab82-a90fd50c9e45.png)

Where is plug-in My_Worlds set?

**Comment by VIQingNiao** [comment]
My English is not very good. It may not be this effect, but this
Give me some time to show

**Comment by bergerkiller** [comment]
Are you talking about chat message prefixes?

**Comment by VIQingNiao** [comment]
![image](https://user-images.githubusercontent.com/46963763/165348003-2f859505-6882-4e71-b5c9-13c2b1f1ad0f.png)

**Comment by VIQingNiao** [comment]
![image](https://user-images.githubusercontent.com/46963763/165348123-a5198806-3eb6-43c1-9578-708310bdfdc4.png)

**Comment by VIQingNiao** [comment]
Add world name alias function
In addition, let plug-in placeholder support this function

Can you achieve it?

**Comment by bergerkiller** [comment]
Yeah should be easy to add. I'll put it somewhere for stuff to do, maybe tomorrow

**Comment by VIQingNiao** [comment]
I don't want to use the default name. I want to use an alias, such as Chinese name "主世界", to express "world"

This will be a very cool thing, and I will thank you. Don't forget to support plug-in placeholder

**Comment by VIQingNiao** [comment]
Oh, alias also supports multiple colors. Thank you, great plug-in developer. Good luck every day

**Comment by bergerkiller** [comment]
Don't worry, I've used PAPI before in SignLink, so I know what you mean.

**Comment by bergerkiller** [comment]
![ScreenShot_2022-04-27 17-21-43](https://user-images.githubusercontent.com/957601/165553348-edac82bc-82d7-4b6b-9f55-20dbcece269d.png)

I went a bit overboard and these all work too:
![ScreenShot 2022-04-27 17 22 33](https://user-images.githubusercontent.com/957601/165553534-4f7f780b-b6eb-4400-aa07-e5439372fcae.jpg)

Alias (/world alias) is only used for placeholderapi atm. Didnt change any localization logic as that has some negative downsides.

Color codes of course work. Do note that for spaces in the alias you need to use "
/world alias "The cool world"

Otherwise the last 'world' is interpreted as the world to set the alias for, and you set "the cool" instead.

Give me a moment to clean things up and itll be on jenkins soon.

**Comment by VIQingNiao** [comment]
Thank you for your efforts. I hope this can not only set aliases for world "world", but also set different aliases for World "world01", "world02" and so on.Set as follows

world alias "&2cool"
world01 alias "&3Beautiful_world"
world02 alias "&4&nCorrupt_world"

**Comment by bergerkiller** [comment]
Yes you can
