### ISSUE TITLE
Wrong order of args in teleport command

### ISSUE THREAD

**Issue by viasnake** [bergerhealer/MyWorlds#34]
Order of tab completion when typing `/mw teleport` command is incorrect.

For example, if you want to teleport `Player1` to `world_A`, the command you should execute is `/mw teleport Player1 world_A`.

However, if you trust tab-completion in-game and type it in, you will complete the command as follows.
Command: `/mw teleport world_A Player1`

If the command is `/mw teleport arg1 arg2`, then World name is suggested in `arg1` and Player name is suggested in `arg2`.

**Expected behavior**
Player name is suggested in `arg1` and World name in `arg2`.

But, given that shortened commands such as `/mw teleport world_A` are common and even mentioned in [wiki](https://wiki.traincarts.net/p/MyWorlds/Commands#Teleport_to_world_spawn), it may be better to change the actual command behavior.
If change it, the last arg will probably be player name.

**Comment by bergerkiller** [comment]
Im conflicted because /tp playername location is the vanilla way, but I made /mw teleport so that you could specify more than one player to be teleported. The same applies to /tpp.

However, it's super confusing if you autocomplete both world names and player names for the second argument. I'll fix it so the first argument completes world names and second-onwards player names.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/MyWorlds/191/ that should do it

**Comment by viasnake** [comment]
Thanks for the fix.
Everything seems to be resolved in the latest build.
